### ISSUE TITLE
question about datasets

### ISSUE THREAD

**Issue by FangHongbiao** [mmalekzadeh/replacement-autoencoder#1]
I read the source code, and find many .npy file loaded  by np.load(), but I don't find the files in project directory. Then I go to the dataset website, and I  find the dataset are matlab format. I want to know how deal with dataset?

**Comment by mmalekzadeh** [comment]
Could you tell me with which dataset you want to work, so I can better answer your issue?

**Comment by FangHongbiao** [comment]
I just want to run the project , but  the files defined in the code can't be find.

**Comment by mmalekzadeh** [comment]
Great. Let me write something for you and other people interested in. I will add a guide to the repo this Friday and will let you know when I add it.

**Comment by FangHongbiao** [comment]
The slides you have submitted seem an example of person moving. But in the demo, no implement about this dataset. I run the project, found some files missing [e.g. opportunity/om1_creating_datasets.py line23, np.loadtxt("S1-Drill.txt"),  and skoda/sm1_creating_sections.py line16, 18, np.loadtxt("left_hand.txt", delimiter=',') , and hand_gesture/hm1_creating_sections.py line 18,19,21,22, np.loadtxt("subject_1_data.txt",delimiter=',')]. Could you tell me where I can get this files?

**Comment by mmalekzadeh** [comment]
No, forget the slides. It was nothing. I will give you the answer very soon. Just wait 1 day.

**Comment by FangHongbiao** [comment]
OK, thank you

**Comment by mmalekzadeh** [comment]
Please have a look at this file: https://github.com/mmalekzadeh/replacement-autoencoder/blob/master/skoda/RAE_on_Skoda_dataset.ipynb

I have also uploaded Skoda dataset .txt files.
For other Datasets, please find related files from the main websites. Links are available in the paper.
